config/routes.rb
Rails.application.routes.draw do

  get 'chats/index'

  get 'chats/show'

  get 'chats/create'

  get 'chats/destroy'

  resources :shoppe_products
  mount Shoppe::Engine => "/shoppe"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    unblocks: 'users/unblocks',
    confirmations: 'users/confirmations'
  }

  get '/users/:id/chef_requests/new' => 'chef_requests#new', as: :new_chef_request
  post '/users/:id/chef_requests' => 'chef_requests#create', as: :post_chef_request

  root 'pages#home'

  get '/about' => 'pages#about'
  get '/home' => 'pages#home'
  get '/profile/:id' => 'pages#profile'

  match '/contact', to: 'contact#new', via: 'get'
  resources "contact", only: [:new, :create]
  
  resources :charges

  get "product/:permalink", to: "products#show", as: "product"
  post "product/:permalink", to: "products#buy", as: "buy"
  post "product/:permalink", to: "products#buy"
  get "basket", to: "orders#show"
  delete "basket", to: "orders#destroy"
  
  match "checkout", to: "orders#checkout", as: "checkout", via: [:get, :patch]
  match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]

  get '/chef/:id' => 'users#chef_profile', as: :chef_profile

  get '/users/:id/follow' => 'followers#create', as: :follow_chef
  delete '/users/:id/unfollow' => 'followers#destroy', as: :un_follow_chef

end

app/models/chat.rb
class Chat < ActiveRecord::Base

	belongs_to :first_member, class_name: User
	belongs_to :second_member, class_name: User

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Squirelfeed Contact Form",
      :to => "mark@squirelfeed.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :followee, class_name: User
  belongs_to :follower, class_name: User

end

app/models/message.rb
class Message < ActiveRecord::Base

	belongs_to :sender, class_name: User
	belongs_to :first_member, class_name: User
	belongs_to :chat
	validates_presence_of :message
end

app/models/shoppe_product.rb
class ShoppeProduct < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :followers       
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

#This is for Stripe subscriptions

def new
end

def create
  # Amount in cents
  @amount = 0

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
  end

  def show
  end

  def create
  end

  def destroy
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def new
    	@contact = Contact.new
  	end

  	def create
    	@contact = Contact.new(params[:contact])
    	@contact.request = request
    	if @contact.deliver
      		flash.now[:notice] = 'Thank you for your message!'
    	else
      	flash.now[:error] = 'Cannot send message.'
      		render :new
    	end
  	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  #This is for Shoppe

	def destroy
  		current_order.destroy
  		session[:order_id] = nil
  		redirect_to root_path, :notice => "Basket emptied successfully."
  	end

  	def checkout
  		@order = Shoppe::Order.find(current_order.id)
	end

	def checkout
  	@order = Shoppe::Order.find(current_order.id)
  	if request.patch?
    	if @order.proceed_to_confirm(params[:order].permit(:first_name, :last_name, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number))
      			redirect_to checkout_payment_path
    	end
  	end
	end

  def payment
    if request.post?
      redirect_to checkout_confirmation_path
    end
  end

  def confirmation
    if request.post?
      current_order.confirm!
      session[:order_id] = nil
      redirect_to root_path, :notice => "Order has been placed successfully!"
    end
  end
  		
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def product
  end

  def index
  end

  def home
  end

  def profile
  	@user = User.find_by(id: params[:id])
  	if @user.present?
      @name = @user.name 
  	else
  		redirect_to root_path, :notice=>"User not found!"
  	end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def chef_profile
  end

  private
  def set_user
    @chef = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/chef_requests_helper.rb
module ChefRequestsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<!--for Stripe subscriptions-->
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<!--For Stripe subscriptions-->
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/orders/_items.html.erb
<!--For Shoppe-->
<table width='100%' border='1'>
  <thead>
    <tr>
      <td>Quantity</td>
      <td>Product</td>
      <td>Sub-Total</td>
      <td>Tax</td>
      <td>Total</td>
    </tr>
  </thead>
  <tbody>
    <% order.order_items.each do |item| %>
    <tr>
      <td><%= item.quantity %></td>
      <td><%= item.ordered_item.full_name %></td>
      <td><%= number_to_currency item.sub_total %></td>
      <td><%= number_to_currency item.tax_amount %></td>
      <td><%= number_to_currency item.total %></td>
    </tr>
    <% end %>

    <% if order.delivery_service %>
    <tr>
      <td></td>
      <td><%= order.delivery_service.name %></td>
      <td><%= number_to_currency order.delivery_price %></td>
      <td><%= number_to_currency order.delivery_tax_amount %></td>
      <td><%= number_to_currency order.delivery_price + order.delivery_tax_amount %></td>
    </tr>
    <% end %>

  </tbody>
  <tfoot>
    <tr>
      <td colspan='4'>Sub-Total</td>
      <td><%= number_to_currency order.total_before_tax %></td>
    </tr>
    <tr>
      <td colspan='4'>Tax</td>
      <td><%= number_to_currency order.tax %></td>
    </tr>
    <tr>
      <td colspan='4'>Total</td>
      <td><%= number_to_currency order.total %></td>
    </tr>
  </tfoot>
</table>

app/views/orders/checkout.html.erb
<!--For Shoppe-->
<h2>Checkout</h2>
<%= render 'items', :order => @order %>

<%= form_for @order, :url => checkout_path do |f| %>
  <dl>
    <dt><%= f.label :first_name, 'Name' %></dt>
    <dd><%= f.text_field :first_name %> <%= f.text_field :last_name %></dd>

    <dt><%= f.label :billing_address1, 'Address' %></dt>
    <dd><%= f.text_field :billing_address1 %></dd>
    <dd><%= f.text_field :billing_address2 %></dd>
    <dd><%= f.text_field :billing_address3 %></dd>
    <dd><%= f.text_field :billing_address4 %></dd>
    <dt><%= f.label :billing_postcode, 'Post code' %></dt>
    <dd><%= f.text_field :billing_postcode %></dd>
    <dd><%= f.collection_select :billing_country_id, Shoppe::Country.ordered, :id, :name, :include_blank => true %></dd>

    <dt><%= f.label :email_address %></dt>
    <dd><%= f.text_field :email_address %></dd>

    <dt><%= f.label :phone_number %></dt>
    <dd><%= f.text_field :phone_number %></dd>

    <dd><%= f.submit 'Continue' %></dd>
  </dl>
<% end %>

app/views/orders/confirmation.html.erb
<!--For Shoppe-->
<h2>Place your order</h2>
<%= render 'items', :order => current_order %>
<%= button_to "Place order" %>

app/views/orders/payment.html.erb
<!--For Shoppe-->
<h2>Make your payment</h2>
<%= form_tag do %>
  <dl>
    <dt><%= label_tag 'card_number' %></dt>
    <dd><%= text_field_tag 'card_number' %></dd>
    <dt><%= label_tag 'expiry' %></dt>
    <dd><%= text_field_tag 'expiry' %></dd>
    <dt><%= label_tag 'security_code' %></dt>
    <dd><%= text_field_tag 'security_code' %></dd>
    <dd><%= submit_tag "Continue" %></dd>
  </dl>
<% end %>

app/views/orders/show.html.erb
<!--For Shoppe-->
<h2>Your basket</h2>
<%= render 'items', :order => current_order %>
<p><%= link_to 'Empty basket', basket_path, :method => :delete %></p>