config/routes.rb
Rails.application.routes.draw do

  get 'chats/index'

  get 'chats/show'

  get 'chats/create'

  get 'chats/destroy'

  resources :shoppe_products
  mount Shoppe::Engine => "/shoppe"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    unblocks: 'users/unblocks',
    confirmations: 'users/confirmations'
  }

  get '/users/:id/chef_requests/new' => 'chef_requests#new', as: :new_chef_request
  post '/users/:id/chef_requests' => 'chef_requests#create', as: :post_chef_request

  root 'pages#home'

  get '/about' => 'pages#about'
  get '/home' => 'pages#home'
  get '/profile/:id' => 'pages#profile'

  match '/contact', to: 'contact#new', via: 'get'
  resources "contact", only: [:new, :create]
  
  resources :charges

  get "product/:permalink", to: "products#show", as: "product"
  post "product/:permalink", to: "products#buy", as: "buy"
  post "product/:permalink", to: "products#buy"
  get "basket", to: "orders#show"
  delete "basket", to: "orders#destroy"
  
  match "checkout", to: "orders#checkout", as: "checkout", via: [:get, :patch]
  match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]

  get '/chef/:id' => 'users#chef_profile', as: :chef_profile

  get '/users/:id/follow' => 'followers#create', as: :follow_chef
  delete '/users/:id/unfollow' => 'followers#destroy', as: :un_follow_chef

end

app/models/chat.rb
class Chat < ActiveRecord::Base

	belongs_to :first_member, class_name: User
	belongs_to :second_member, class_name: User

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Squirelfeed Contact Form",
      :to => "mark@squirelfeed.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :followee, class_name: User
  belongs_to :follower, class_name: User

end

app/models/message.rb
class Message < ActiveRecord::Base

	belongs_to :sender, class_name: User
	belongs_to :first_member, class_name: User
	belongs_to :chat
	validates_presence_of :message
end

app/models/shoppe_product.rb
class ShoppeProduct < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :followers       
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
  end

  def show
  end

  def create
  end

  def destroy
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  #This is for Shoppe

	def destroy
  		current_order.destroy
  		session[:order_id] = nil
  		redirect_to root_path, :notice => "Basket emptied successfully."
  	end

  	def checkout
  		@order = Shoppe::Order.find(current_order.id)
	end

	def checkout
  	@order = Shoppe::Order.find(current_order.id)
  	if request.patch?
    	if @order.proceed_to_confirm(params[:order].permit(:first_name, :last_name, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number))
      			redirect_to checkout_payment_path
    	end
  	end
	end

  def payment
    if request.post?
      redirect_to checkout_confirmation_path
    end
  end

  def confirmation
    if request.post?
      current_order.confirm!
      session[:order_id] = nil
      redirect_to root_path, :notice => "Order has been placed successfully!"
    end
  end
  		
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def product
  end

  def index
  end

  def home
  end

  def profile
  	@user = User.find_by(id: params[:id])
  	if @user.present?
      @name = @user.name 
  	else
  		redirect_to root_path, :notice=>"User not found!"
  	end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def chef_profile
  end

  private
  def set_user
    @chef = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/chef_requests_helper.rb
module ChefRequestsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<!-- begin ruby for authentication -->
<% if !user_signed_in? %>
  <%= render '/layouts/nav_guest' %>
<% else %>
  <%= render '/layouts/nav_user' %>
<% end %>

app/views/layouts/_nav_guest.html.erb
<style>
    /* ==========================================================================
Navigation Style
========================================================================== */
.myNavbar   {
    background-color: #000000;
    color:#222;
    border: 1px solid #fff;
 }
.navbar-default {
  margin-bottom: 0;
  border: none;
}
.navbar-default .nav > li > a {
  font-size: 14px;
  color: #fff;
  font-weight: 700;
  text-transform: uppercase;
  padding: 35px 15px;
  -moz-transition: all 0.3s ease-in-out;
  -o-transition: all 0.3s ease-in-out;
  -webkit-transition: all 0.3s ease-in-out;
  transition: all 0.3s ease-in-out;
}
.navbar-default .nav > li > a:hover,
.navbar-default .nav > li > a:focus,
.navbar-default .nav > li > a:active {
  color: #a3a3a3;
}
.navbar-default .social-media {
  float: right;
  padding: 0 15px;
}
.navbar-default .social-media i {
  font-size: 22px;
}
.navbar-default .navbar-nav > .active > a,
.navbar-default .navbar-nav > .active > a:focus,
.navbar-default .navbar-nav > .active > a:hover {
  background: transparent;
  color: #a3a3a3;
}
.top-nav-collapse {
  background: #24242a;
}
.navbar-brand img {
  width: 50px;
  height: 50px;
}
.top-nav-collapse .nav > li > a {
  padding: 30px 15px;
}
</style>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><img src="/assets/logo/logo_brown_no_text.png" alt="logo"></a>
    </div>
    <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav">
          <li><a href="/home">Home</a></li>
        </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/basket"><span class="glyphicon glyphicon-shopping-cart"></span> Cart</a></li>
        <li><%= link_to "Checkout", checkout_path %></li>
        <div class="social-media hidden-sm hidden-xs">
          <ul class="nav navbar-nav">
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
          </ul>
        </div>
        <li><%= link_to('Sign In', new_user_session_path) %></li>
        <li><%= link_to('Sign Up', new_user_registration_path) %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_nav_user.html.erb
<style>
    /* ==========================================================================
Navigation Style
========================================================================== */
.myNavbar   {
    background-color: #000000;
    color:#222;
    border: 1px solid #fff;
 }
.navbar-default {
  margin-bottom: 0;
  border: none;
}
.navbar-default .nav > li > a {
  font-size: 14px;
  color: #fff;
  font-weight: 700;
  text-transform: uppercase;
  padding: 35px 15px;
  -moz-transition: all 0.3s ease-in-out;
  -o-transition: all 0.3s ease-in-out;
  -webkit-transition: all 0.3s ease-in-out;
  transition: all 0.3s ease-in-out;
}
.navbar-default .nav > li > a:hover,
.navbar-default .nav > li > a:focus,
.navbar-default .nav > li > a:active {
  color: #a3a3a3;
}
.navbar-default .social-media {
  float: right;
  padding: 0 15px;
}
.navbar-default .social-media i {
  font-size: 22px;
}
.navbar-default .navbar-nav > .active > a,
.navbar-default .navbar-nav > .active > a:focus,
.navbar-default .navbar-nav > .active > a:hover {
  background: transparent;
  color: #a3a3a3;
}
.top-nav-collapse {
  background: #24242a;
}
.navbar-brand img {
  width: 50px;
  height: 50px;
}
.top-nav-collapse .nav > li > a {
  padding: 30px 15px;
}
</style>

<nav class="navbar navbar-default navbar-fixed-top myNavbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home"><img src="/assets/logo/logo_brown_no_text.png" class="img-responsive" alt="logo"></a>
    </div>
    <div class="collapse navbar-collapse text-center" id="navbar">
      <ul class="nav navbar-nav">
        <li><a href="/home">Home</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <li><a href="/basket"><span class="glyphicon glyphicon-shopping-cart"></span>Cart</a></li>
      <li><%= link_to "Checkout", checkout_path %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="/profile/<%=current_user.id %>">Profile</a></li>
          <li><a href="#">Settings</a></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to('Edit Profile', edit_user_registration_path) %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to('Logout', destroy_user_session_path, :method=>:delete) %></li>
        </ul>
      </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if current_order %>
    <p style="border:1px solid black;padding:10px;">
      You have <%= pluralize current_order.total_items, 'item'%> in your basket which cost
      <%= number_to_currency current_order.total_before_tax %>.
    </p>
    <% end %>
    <%= link_to "View basket", basket_path %>
    

    <!--navbar render code -->
    <%= render '/layouts/nav' %>
    <br /><br /><br />
    <% if notice %>
      <div style="width: 50%; margin-left: 25%;" class = 'alert alert-warning'><%= notice %></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!--For Stripe subscriptions-->
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<!doctype html>
<% content_for :title, "About" %>
<html class="no-js" lang="en" dir="ltr">
  <head>
  	<title>About</title>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/foundation.css">
    <link rel="stylesheet" href="css/app.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js">
  	</script>
  	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
  	</script>
    <style>

      @font-face {
        font-family: Brandon Grotesque;
        src: url("/assets/Brandon Grotesque/Brandon_reg.otf") format("truetype");
      }
      h1 { font-family: 'Brandon Grotesque', Times, serif; }
    </style>
  </head>

<body>
    <header class="intro-header" style="background-image: url('img/contact-bg.jpg')">
    	<div class="row">
  			<div class="jumbotron">
  				<div class="container text-center">
    			<h1></h1>
  			</div>
		</div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>What is Squirel?</h1>
                        <hr class="small">
                        <span class="subheading">Good question... we'll get to that :)</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            
        </div>
    </div>

    <hr>

    <!-- Footer -->
	<footer class="container-fluid text-center">
        
    </footer>

</body>

</html>

app/views/pages/profile.html.erb
<!doctype html>
<% content_for :title, "My Profile" %>
<html lang="en">

<head>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8">

    <title>Squirel</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    <!-- Bootstrap Css -->
    <link href="/assets/bootstrap-assets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Style -->
    <link href="/assets/main.css" rel="stylesheet">

    <!-- Icons Font -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

  <body>
  	<div class="row">
  		<div class="jumbotron">
  			<div class="container text-center">
    		<h1>
			</h1>
  		</div>
	</div>

  		<div class="col-xs-3">
  			<div class="panel panel-default">
  				<div class="panel-body">
  					<img src="/assets/profile_pic_default.png">
  					<p class="profile">
  						<%= @name %>'s Profile</p>
  				</div>
			</div>
  		</div>
  		<div class="col-xs-6">
			<div class="panel panel-default">
  				<div class="panel-body">
  					<p class="feed">Eventually, you'll have a feed here!</p>
  				</div>
			</div>  	
		</div>
  		<div class="col-xs-3">
  			<div class="panel panel-default">
  				<div class="panel-body">
  					<p class="about">...and all your settings and stuff will go here!
  					</p>
  				</div>
			</div>
  		</div>
  	</div>
    <% if !@user.has_submitted_chef_request? %>
      <%= link_to 'Become a chef', new_chef_request_path(@user.id), class: 'btn btn-primary' %>
    <% end %>
    <script src="js/vendor/jquery.js"></script>
    <script src="js/vendor/what-input.js"></script>
    <script src="js/vendor/foundation.js"></script>
    <script src="js/app.js"></script>
  </body>
</html>